inputs:
  codecov_secret:
    description: |
      Should be copy of secrets.CODECOV_TOKEN from calling environment.
    required: true


runs:
  using: "composite"
  steps:
    # Load a specific version of Python
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
        architecture: x64

    - name: Install deps
      shell: bash
      run: make github_actions
      env:
        SSH_AUTH_SOCK: /tmp/ssh_agent.sock

    - if: ${{env.coverage_type == 'ondemand' }}
      shell: bash
      name: Run on-demand coverage
      run: make ondemandcoverage

    - if: ${{ env.coverage_type == 'totalcoverage'}}
      shell: bash
      name: Run total coverage
      run: make totalcoverage

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      env:
        CODECOV_TOKEN: ${{ inputs.codecov_secret }}
      with:
        files: ./.coverage,./coverage.xml
        fail_ci_if_error: trueyml