# This workflow runs automatic code style checks.

# We need a workflow name to be able to schedule it from Github UI
name: style

on:
  # Triggers the workflow on push to main
  push:
    branches:
      - main
  # Triggers the workflow on any PR
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # The job ID has to match repo settings for PR required checks
  style:
    runs-on: ubuntu-latest

    # Run jobs for a couple of Python versions.
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]

    name: Style - Python ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v2

      - name: Get orquestra-quantum
        uses: actions/checkout@v2
        with:
          repository: zapatacomputing/orquestra-quantum
          path: orquestra-quantum

      # Installs project, checks codestyle
      - uses: ./subtrees/z_quantum_actions/actions/style
